import { TEMPLATE } from './params';

const ASSETS_PATH = 'assets';
const SOURCE_PATH = 'src';
const PUBLIC_PATH = 'public';
const CORE_PATH = 'core';
const ICONS_PATH = 'icons';
const FAVICONS_PATH = 'favicons';
const FONTS_PATH = 'fonts';
const IMAGES_PATH = 'img';
const SCRIPTS_PATH = 'js';
const STYLES_PATH = 'scss';
const TEMPLATES_PATH = 'templates';
const TRANSLATIONS_PATH = 'translations';

const SOURCE_ASSETS_PATH = `${SOURCE_PATH}/${ASSETS_PATH}`;
const TEMPLATE_ASSETS_PATH = `${SOURCE_ASSETS_PATH}/${TEMPLATE}`;
const PUBLIC_ASSETS_PATH = `${PUBLIC_PATH}/${ASSETS_PATH}`;

const FONTS_SRC = `${TEMPLATE_ASSETS_PATH}/${FONTS_PATH}`;
const IMAGES_SRC = `${TEMPLATE_ASSETS_PATH}/${IMAGES_PATH}`;
const SCRIPTS_SRC = `${TEMPLATE_ASSETS_PATH}/${SCRIPTS_PATH}`;
const STYLES_SRC = `${TEMPLATE_ASSETS_PATH}/${STYLES_PATH}`;
const TEMPLATES_SRC = `${SOURCE_PATH}/${TEMPLATES_PATH}`;
const TEMPLATE_SRC = `${TEMPLATES_SRC}/${TEMPLATE}`;

const FONTS_DEST = `${PUBLIC_ASSETS_PATH}/${FONTS_PATH}`;
const IMAGES_DEST = `${PUBLIC_ASSETS_PATH}/${IMAGES_PATH}`;
const SCRIPTS_DEST = `${PUBLIC_ASSETS_PATH}/${SCRIPTS_PATH}`;
const STYLES_DEST = `${PUBLIC_ASSETS_PATH}/css`;

const FONTS_ASSETS = `/${ASSETS_PATH}/${FONTS_PATH}`;
const IMAGES_ASSETS = `/${ASSETS_PATH}/${IMAGES_PATH}`;
const SCRIPTS_ASSETS = `/${ASSETS_PATH}/${SCRIPTS_PATH}`;
const STYLES_ASSETS = `/${ASSETS_PATH}/css`;

export {
  CORE_PATH,
  FAVICONS_PATH,
  FONTS_DEST,
  FONTS_PATH,
  FONTS_SRC,
  ICONS_PATH,
  IMAGES_DEST,
  IMAGES_PATH,
  IMAGES_SRC,
  PUBLIC_PATH,
  SCRIPTS_DEST,
  SCRIPTS_PATH,
  SCRIPTS_SRC,
  SOURCE_ASSETS_PATH,
  STYLES_DEST,
  STYLES_PATH,
  STYLES_SRC,
  FONTS_ASSETS,
  IMAGES_ASSETS,
  SCRIPTS_ASSETS,
  STYLES_ASSETS,
  TEMPLATES_SRC,
  TEMPLATE_ASSETS_PATH,
  TEMPLATE_SRC,
  TRANSLATIONS_PATH
};
